name: Release

on:
  push:
    tags:
      - v*
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            ref: ${{ github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache-dependency-path: pnpm-lock.yaml
      - name: Enable corepack 
        run: corepack enable
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Set publishing config
        run: |
         pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish
        run: pnpm publish
      - name: Create Github Release
        run: |
          pnpm dlx changelogen gh release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
